Project skeleton
noahsnative/voltron pull request #2
Opened 2020-02-14 22:20 UTC by skhalash

# What's done?

Just a simple hello-world-like web service application. Added a Dockerfile a Makefile. Nothing fancy, but should be enough to test a CI pipeline against.

2020-02-22 23:02 UTC, cfreemoser requested changes
Let's merge my branch first into yours

2020-02-26 12:18 UTC, cfreemoser requested changes

2020-02-26 12:18 UTC, cfreemoser commented on Makefile
> +image:
maybe rename it to docker

2020-02-26 12:18 UTC, cfreemoser commented on Makefile
> +image:
adding make lint

2020-02-26 12:18 UTC, cfreemoser commented on .github/workflows/dockerpush.yml
> +jobs:
add lint

2020-02-26 12:18 UTC, cfreemoser commented on internal/injector/server_test.go
> +	admitterMock := &mocks.Admitter{}
It is a stub, rename the variable

2020-02-26 12:18 UTC, cfreemoser commented on internal/injector/server_test.go
> +	admitterMock := &mocks.Admitter{}
It is a stub, rename the variable

2020-02-29 18:08 UTC, skhalash commented on Makefile
> +image:
Yeah, makes sense

2020-02-29 19:47 UTC, skhalash commented on Makefile
> +image:
Done

2020-02-29 19:47 UTC, skhalash commented on .github/workflows/dockerpush.yml
> +jobs:
Done

2020-03-08 11:53 UTC, merged